( Anglais vivre maison rouge )
( Suédois avoir domestiques animaux chiens )
( personne boire the etre Danois )
( maison verte etre gauche maison blanche )
( propriétaire maison verte boire cafe )
( personne fumer Pall_Mall avoir oiseaux )
( propriétaire maison jaune fumer Dunhill )
( personne vivre maison centre boire jus orange )
